# Generated by Django 4.2.16 on 2025-01-30 13:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="user",
        ),
        migrations.RemoveField(
            model_name="useractivity",
            name="profile",
        ),
        migrations.RemoveField(
            model_name="userpreferences",
            name="profile",
        ),
        migrations.DeleteModel(
            name="AdditionalInfo",
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
        migrations.DeleteModel(
            name="UserActivity",
        ),
        migrations.DeleteModel(
            name="UserPreferences",
        ),
    ]
