# Generated by Django 4.2.16 on 2025-01-31 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0005_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="additionalinfo",
            name="custom_field",
            field=models.TextField(blank=True),
        ),
    ]
