# Generated by Django 5.0.3 on 2025-02-05 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_district_rating_street_news_user_news_views_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_related', to='base.news'),
        ),
        migrations.AlterField(
            model_name='news',
            name='reviews',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_reviews', to='base.reviews'),
        ),
    ]
