# Generated by Django 5.0.3 on 2025-02-05 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_reviews_news_alter_news_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='news',
        ),
    ]
