# Generated by Django 5.0.3 on 2025-02-05 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_reviews_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.district'),
        ),
        migrations.AlterField(
            model_name='news',
            name='reviews',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.reviews'),
        ),
    ]
