# Generated by Django 5.0.3 on 2025-03-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_additionalinfo_options_alter_avatar_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedetailpage',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='URL-идентификатор'),
        ),
    ]
