# Generated by Django 5.0.3 on 2025-03-18 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_servicedetailpage_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceDetailPage',
        ),
    ]
