# Generated by Django 5.0.3 on 2025-03-20 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_delete_servicedetailpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='image_dop',
        ),
        migrations.AddField(
            model_name='service',
            name='additional_image',
            field=models.ImageField(blank=True, null=True, upload_to='service_images/', verbose_name='Дополнительное изображение'),
        ),
        migrations.AddField(
            model_name='service',
            name='full_description',
            field=models.TextField(blank=True, null=True, verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='service',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='Мета-описание'),
        ),
        migrations.AddField(
            model_name='service',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета-заголовок'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='service_images/', verbose_name='Основное изображение'),
        ),
    ]
