# Generated by Django 5.0.3 on 2025-03-20 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_remove_service_image_dop_service_additional_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='additional_image',
            new_name='dop_image',
        ),
        migrations.RemoveField(
            model_name='service',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='meta_title',
        ),
        migrations.AddField(
            model_name='service',
            name='dop_info',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AddField(
            model_name='service',
            name='dop_text',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительный текст'),
        ),
    ]
