# Generated by Django 5.0.3 on 2025-03-20 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_rename_additional_image_service_dop_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='dop_image',
        ),
        migrations.RemoveField(
            model_name='service',
            name='dop_info',
        ),
        migrations.RemoveField(
            model_name='service',
            name='dop_text',
        ),
        migrations.CreateModel(
            name='ServiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_description', models.TextField(blank=True, null=True, verbose_name='Полное описание')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Дополнительный текст')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='base.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Детальная информация об услуге',
                'verbose_name_plural': 'Детальная информация об услугах',
            },
        ),
        migrations.CreateModel(
            name='ServiceGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='service_gallery/', verbose_name='Изображение')),
                ('service_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='base.servicedetail', verbose_name='Галерея')),
            ],
        ),
    ]
