# Generated by Django 5.0.3 on 2025-03-20 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_remove_service_dop_image_remove_service_dop_info_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicedetail',
            options={'verbose_name': 'Детальная информация об услуге'},
        ),
        migrations.AlterModelOptions(
            name='servicegallery',
            options={'verbose_name': 'Изображение для услуги'},
        ),
        migrations.RemoveField(
            model_name='service',
            name='full_description',
        ),
        migrations.RemoveField(
            model_name='servicedetail',
            name='info',
        ),
        migrations.RemoveField(
            model_name='servicedetail',
            name='price',
        ),
        migrations.RemoveField(
            model_name='servicedetail',
            name='text',
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='dop_text',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительный текст'),
        ),
        migrations.CreateModel(
            name='DopInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок')),
                ('image', models.ImageField(blank=True, null=True, upload_to='service_info/', verbose_name='Изображение')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Информация')),
                ('service_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dop_info', to='base.servicedetail', verbose_name='Дополнительная информация')),
            ],
            options={
                'verbose_name': 'Дополнительная информация',
            },
        ),
    ]
