# Generated by Django 5.0.3 on 2025-03-20 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_servicedetail_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dopinfo',
            options={'verbose_name': 'Доп. информация для услуги', 'verbose_name_plural': 'Доп. информация для услуги'},
        ),
        migrations.AlterModelOptions(
            name='servicedetail',
            options={'verbose_name': 'Детальная информация об услуге', 'verbose_name_plural': 'Детальная информация об услугах'},
        ),
        migrations.AlterModelOptions(
            name='servicegallery',
            options={'verbose_name': 'Изображение для услуги', 'verbose_name_plural': 'Изображения для услуги'},
        ),
        migrations.RemoveField(
            model_name='dopinfo',
            name='image',
        ),
        migrations.AddField(
            model_name='dopinfo',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='dopinfo',
            name='service_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dop_info', to='base.servicedetail', verbose_name='Доп. информация для услуги'),
        ),
    ]
