# Generated by Django 5.0.3 on 2025-03-20 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_dopinfo_options_alter_servicedetail_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dopinfo',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='Заголовок'),
        ),
    ]
