# Generated by Django 5.0.3 on 2025-03-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_alter_dopinfo_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicedetail',
            options={'verbose_name': 'Детальная информация об услуге', 'verbose_name_plural': 'Детальная информация об услуге'},
        ),
        migrations.RemoveField(
            model_name='dopinfo',
            name='name',
        ),
        migrations.AddField(
            model_name='dopinfo',
            name='subtitle',
            field=models.TextField(blank=True, null=True, verbose_name='Подзаголовок'),
        ),
    ]
