# Generated by Django 5.0.3 on 2025-03-21 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_alter_servicedetail_options_remove_dopinfo_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDetailDopInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True, verbose_name='Заголовок')),
                ('subtitle', models.TextField(blank=True, null=True, verbose_name='Подзаголовок')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Информация')),
                ('service_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dop_info', to='base.servicedetail', verbose_name='Доп. информация для услуги')),
            ],
            options={
                'verbose_name': 'Доп. информация для услуги',
                'verbose_name_plural': 'Доп. информация для услуги',
            },
        ),
        migrations.DeleteModel(
            name='DopInfo',
        ),
    ]
